server:
  port: 8082
spring:
  redis:
    host: 10.20.38.64
    password: ''
    port: 6379

sc:
  sso:
    app-id: client1
    app-secret: 123456
    serverUrl: http://10.20.38.64:8081
    timeout: 7200
    enabled: true

